// @vitest-environment jsdom
import React from "react";
import { cleanup, render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, describe, expect, it, vi } from "vitest";
import { FeedbackTable } from "@/app/admin/feedback-table";
import { UserManagement } from "@/app/admin/user-management";
const fid="10000000-0000-4000-8000-000000000001", aid="00000000-0000-4000-8000-000000000002";
const item={id:fid,agentId:aid,agentUsername:"agent-02",question:"列表中的问题",aiOriginal:"列表原稿",finalDraft:"列表最终稿",action:"modified",discardReason:null,reviewStatus:"pending",createdAt:"2026-08-12T02:00:00.000Z"};
const detail={...item,question:"完整客户问题",aiOriginal:"完整 AI 原稿",finalDraft:"完整客服最终稿",faqSnapshot:{faq:"FAQ 快照"},productSnapshot:{product:"商品快照"},versions:{model:"m1",prompt:"p1",system:"s1",knowledge:"k1"}};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json"}});
afterEach(()=>{cleanup();vi.unstubAllGlobals();});
describe("管理员反馈界面",()=>{
it("六筛选同用于列表导出且重置页",async()=>{const urls:string[]=[];vi.stubGlobal("fetch",vi.fn(async(i:string|URL|Request)=>{urls.push(String(i));return json({items:[item]});}));const b=userEvent.setup();render(<FeedbackTable/>);await screen.findByText("列表中的问题");await b.type(screen.getByLabelText("客服 ID"),aid);await b.selectOptions(screen.getByLabelText("操作"),"modified");await b.selectOptions(screen.getByLabelText("弃用原因"),"wrong_product");await b.selectOptions(screen.getByLabelText("审核状态"),"queued");await b.type(screen.getByLabelText("开始时间"),"2026-08-01");await b.type(screen.getByLabelText("结束时间"),"2026-08-12");await b.click(screen.getByRole("button",{name:"筛选反馈"}));const list=new URL(urls.at(-1)!,"http://x"),exp=new URL((screen.getByRole("link",{name:"导出 CSV"})as HTMLAnchorElement).href);for(const [k,v]of Object.entries({agentId:aid,action:"modified",discardReason:"wrong_product",reviewStatus:"queued",from:"2026-08-01",to:"2026-08-12"})){expect(list.searchParams.get(k)).toBe(v);expect(exp.searchParams.get(k)).toBe(v);}expect(list.searchParams.get("page")).toBe("1");});
it("详情失败保留并重试出完整快照版本",async()=>{let n=0;vi.stubGlobal("fetch",vi.fn(async(i:string|URL|Request)=>{const u=String(i);if(u==="/api/admin/feedback")return json({items:[item]});if(u===`/api/admin/feedback/${fid}`)return ++n===1?json({},500):json(detail);throw 0;}));const b=userEvent.setup();render(<FeedbackTable/>);await b.click(await screen.findByRole("button",{name:"列表中的问题"}));expect((await screen.findByRole("alert")).textContent).toContain("详情加载失败");expect(screen.getByText("列表中的问题")).toBeTruthy();await b.click(screen.getByRole("button",{name:"重试详情"}));expect(await screen.findByText("完整客户问题")).toBeTruthy();for(const t of["完整 AI 原稿","完整客服最终稿","m1","p1","s1","k1"])expect(screen.getByText(new RegExp(t))).toBeTruthy();for(const t of["FAQ 快照","商品快照"])expect(screen.getAllByText(new RegExp(t)).length).toBeGreaterThanOrEqual(2);expect(screen.queryByRole("button",{name:/发布/})).toBeNull();});
it("列表失败保留筛选和结果",async()=>{let n=0;vi.stubGlobal("fetch",vi.fn(async()=>++n===1?json({items:[item]}):json({},500)));const b=userEvent.setup();render(<FeedbackTable/>);await screen.findByText("列表中的问题");await b.type(screen.getByLabelText("客服 ID"),aid);await b.click(screen.getByRole("button",{name:"筛选反馈"}));expect((await screen.findByRole("alert")).textContent).toContain("反馈加载失败");expect(screen.getByText("列表中的问题")).toBeTruthy();expect((screen.getByLabelText("客服 ID")as HTMLInputElement).value).toBe(aid);});});
describe("管理员账号界面",()=>{
it("创建错误保留表单成功才显密码",async()=>{let n=0;vi.stubGlobal("fetch",vi.fn(async(i:string|URL|Request,o?:RequestInit)=>{if(String(i)==="/api/admin/users"&&(!o?.method||o.method==="GET"))return json({items:[{id:aid,username:"old",display_name:"旧客服",role:"agent",status:"active"}]});if(++n===1)return json({error:"username_exists"},409);if(n===2)throw 0;return json({temporaryPassword:"temporary-secret"},201);}));const b=userEvent.setup();render(<UserManagement/>);await screen.findByText(/旧客服/);await b.type(screen.getByLabelText("用户名"),"agent_02");await b.type(screen.getByLabelText("显示名称"),"客服二号");const s=screen.getByRole("button",{name:"创建账号"});await b.click(s);expect((await screen.findByRole("alert")).textContent).toContain("用户名已存在");expect((screen.getByLabelText("用户名")as HTMLInputElement).value).toBe("agent_02");await b.click(s);expect((await screen.findByRole("alert")).textContent).toContain("创建账号失败");await b.click(s);expect(await screen.findByText("temporary-secret")).toBeTruthy();});
it("停用错误保留列表密码并重试",async()=>{let n=0;vi.stubGlobal("fetch",vi.fn(async(i:string|URL|Request,o?:RequestInit)=>{if(String(i)==="/api/admin/users"&&o?.method==="POST")return json({temporaryPassword:"keep-secret"},201);if(String(i)==="/api/admin/users")return json({items:[{id:aid,username:"old",display_name:"旧客服",role:"agent",status:"active"}]});if(String(i)===`/api/admin/users/${aid}`)return ++n===1?json({},500):json({ok:true});throw 0;}));const b=userEvent.setup();render(<UserManagement/>);await screen.findByText(/旧客服/);await b.type(screen.getByLabelText("用户名"),"agent_03");await b.type(screen.getByLabelText("显示名称"),"客服三号");await b.click(screen.getByRole("button",{name:"创建账号"}));await screen.findByText("keep-secret");await b.click(screen.getByRole("button",{name:"停用账号"}));expect((await screen.findByRole("alert")).textContent).toContain("停用账号失败");expect(screen.getByText(/旧客服/)).toBeTruthy();expect(screen.getByText("keep-secret")).toBeTruthy();await b.click(screen.getByRole("button",{name:"停用账号"}));await waitFor(()=>expect(n).toBe(2));});});
